
# -*- coding: utf-8 -*-
# src/report_generator.py
"""
Report generators (PDF & PPTX) for GenSight-Issue-Insight-Automator.

- Auto-creates `reports/<MONTH>/` and `/charts`
- PDF: Title + key metrics + charts (multiple pages if needed)
- PPTX: Title, key highlights, one slide per chart
"""

import os
from typing import List, Dict, Optional
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from pptx import Presentation
from pptx.util import Inches


def ensure_month_folder(month_label: str) -> str:
    folder = f"reports/{month_label}"
    os.makedirs(folder, exist_ok=True)
    os.makedirs(os.path.join(folder, "charts"), exist_ok=True)
    return folder


def generate_pdf_report(
    summary: Dict,
    month_label: str,
    charts: Optional[List[str]] = None,
    output_path: Optional[str] = None,
) -> str:
    folder = ensure_month_folder(month_label)
    if output_path is None:
        output_path = os.path.join(folder, f"Monthly_Report_{month_label}.pdf")

    c = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4

    # Title page
    c.setFont("Helvetica-Bold", 18)
    c.drawString(40, height - 60, f"Monthly Issue Report — {month_label}")

    c.setFont("Helvetica", 12)
    y = height - 100
    c.drawString(40, y, f"Status: {summary.get('by_status', {})}")
    y -= 20
    c.drawString(40, y, f"Issue Types: {summary.get('by_issue_type', {})}")
    y -= 20
    eng = list(summary.get("by_engineer", {}).items())[:3]
    c.drawString(40, y, f"Top Engineers: {eng}")

    # Charts pages
    if charts:
        c.showPage()
        c.setFont("Helvetica-Bold", 16)
        c.drawString(40, height - 60, "Charts")
        y_img = height - 120
        for p in charts:
            try:
                img = ImageReader(p)
                c.drawImage(img, 40, y_img - 220, width=520, height=200, preserveAspectRatio=True, anchor="c")
                y_img -= 240
                if y_img < 140:
                    c.showPage()
                    c.setFont("Helvetica-Bold", 16)
                    c.drawString(40, height - 60, "Charts (contd.)")
                    y_img = height - 120
            except Exception:
                # Skip any chart that fails to load
                continue

    c.showPage()
    c.save()
    return output_path


def generate_ppt_report(
    summary: Dict,
    month_label: str,
    charts: Optional[List[str]] = None,
    output_path: Optional[str] = None,
) -> str:
    folder = ensure_month_folder(month_label)
    if output_path is None:
        output_path = os.path.join(folder, f"Monthly_Issue_Insights_{month_label}.pptx")

    prs = Presentation()

    # Title slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = f"Monthly Issue Insights — {month_label}"
    slide.placeholders[1].text = "Auto-generated by GenSight-Issue-Insight-Automator"

    # Key highlights
    slide2 = prs.slides.add_slide(prs.slide_layouts[1])
    slide2.shapes.title.text = "Key Highlights"
    tf = slide2.placeholders[1].text_frame
    tf.clear()
    p = tf.paragraphs[0]
    p.text = f"Status: {summary.get('by_status', {})}"
    p.level = 0
    p = tf.add_paragraph()
    p.text = f"Issue Types: {summary.get('by_issue_type', {})}"
    p.level = 0
    p = tf.add_paragraph()
    eng = list(summary.get("by_engineer", {}).items())[:3]
    p.text = f"Top Engineers: {eng}"
    p.level = 0

    # Chart slides
    if charts:
        for pth in charts:
            slide3 = prs.slides.add_slide(prs.slide_layouts[5])
            slide3.shapes.title.text = os.path.basename(pth).replace("_", " ").replace(".png", "")
            left, top, height = Inches(1), Inches(1.5), Inches(4.5)
            try:
                slide3.shapes.add_picture(pth, left, top, height=height)
            except Exception:
                # Skip if the image cannot be read
                pass

    prs.save(output_path)
    return output_path